openapi: 3.0.0
info:
  title: Express API Documentation
  version: 1.0.0
  description: Documentation for my Express.js API
paths:
  /users:
    get:
      summary: Get all users
      description: Retrieve a list of all users.
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'  # Reference to User schema

components:
  schemas:
    User:  # Definition of User schema
      type: object
      properties:
        id:
          type: integer
          description: The user's ID.
        name:
          type: string
          description: The user's name.